### ISSUE TITLE
Fundamentals.ProtoBuf

### ISSUE THREAD

**Issue by lgadina** [fundamentalslib/fundamentals5#1]
Hi.
Protobuf is no longer supported?

**Comment by fundamentalslib** [comment]
It will be added soon. It needs some refactoring for Fundamentals 5.

**Comment by fundamentalslib** [comment]
Hi

See sources here:

https://github.com/fundamentalslib/fundamentals5/tree/master/Source/ProtocolBuffers

Binary for code generator here:

https://github.com/fundamentalslib/ProtoBufCodeGen-binaries
