### ISSUE TITLE
Function is only defined on windows "SOCKETLIB_WIN"

### ISSUE THREAD

**Issue by sikofitt** [fundamentalslib/fundamentals5#12]
This fails on Linux because this function result -
https://github.com/fundamentalslib/fundamentals5/blob/9a078628007eaa40a66ae3f6bd6ead8e285c3014/Source/Sockets/flcSocketLib.pas#L1810-L1814

Is only defined for Windows - 
https://github.com/fundamentalslib/fundamentals5/blob/9a078628007eaa40a66ae3f6bd6ead8e285c3014/Source/Sockets/flcSocketLib.pas#L474-L476

**Comment by butlerdj** [comment]
Latest master release compiles under Delphi 10.2 Linux.
