### ISSUE TITLE
pbEncodeFieldBytes has 5 params, but used with 4.

### ISSUE THREAD

**Issue by dyvniy** [fundamentalslib/fundamentals5#2]
I try to compile this project & find this issue.

**Comment by butlerdj** [comment]
Did you manage to solve this? If not, which file and line number?

**Comment by dyvniy** [comment]
In PbProtocolMessages.pas
line 761: I := pbEncodeFieldBytes(P^, L, 5, A.Idk); 
and else.
Version of this function for RawByteString need one else argument - buffer.
But have no in this realisation.
pbDecodeFieldBytes has same error. 

In attachment I give a project how I try to use fundamentals.
You can see errors there.

15.04.2016, 00:43, "butlerdj" <notifications@github.com>:
> Did you manage to solve this? If not, which file and line number?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub

--
С уважением, Николай Вовк.

**Comment by butlerdj** [comment]
I didn't get the attachment, please send it to fundamentals.library@gmail.com

**Comment by adan830** [comment]
i have the same problem, I try to make some test with the fundamentals5 protocolbuffers, but it can't compile success;(ps: the MyMessage.proto file works well with c++);
  the error is:
  [Error] pbMyMessageMessages.pas(243): Not enough actual parameters;(I := pbEncodeFieldBytes(P^, L, 2, A.Passwd);)
  [Error] pbMyMessageMessages.pas(288): Not enough actual parameters;(2 : pbDecodeFieldBytes(Field, A^.Passwd);)
  [Error] pbMyMessageMessages.pas(341): Not enough actual parameters;(I := pbEncodeFieldBytes(P^, L, 2, A.Name);)
  [Error] pbMyMessageMessages.pas(389): Not enough actual parameters;(2 : pbDecodeFieldBytes(Field, A^.Name);)

I think the lib has some problem with the type "bytes";

Hope you to check and solve it; Thanks very much;

PS1: I am very sorry for my poor English. :(;

PS2: The file is in the attachment, i have change the file extension, please change it back;

PS3: I also send a mail to fundamentals.library@gmail.com

thanks for your help!	  





[MyMessage.proto.txt](https://github.com/fundamentalslib/fundamentals5/files/663414/MyMessage.proto.txt)
[pbMyMessageMessages.pas.txt](https://github.com/fundamentalslib/fundamentals5/files/663415/pbMyMessageMessages.pas.txt)
