### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jkour** [fundamentalslib/fundamentals5#25]
Hi guys,
I can produce documentation for the whole library like this: http://docs.casbin4d.kouraklis.com/
Would you be interested to add it in the repo?
Thanks

**Comment by butlerdj** [comment]
Hi there

Thanks for the suggestion. It looks nice. Some questions:

1. How is it hosted and is it free to use?

2. How easy is it to update?

3. Is it possible to edit to add more details?

**Comment by jkour** [comment]
Hi,

I've got this package:
http://www.devjetsoftware.com/products/documentation-insight/

which generates the docs automatically.

Regarding your questions:

1. No it is not free. Once the html files are generated, you can open the index file in a browser locally but the limitation is that the left-side panel with the javascript menu does not work as browsers block some scripts locally. But this does not stop you to explore the libraries etc. You can setup a local server but this is slightly more complex task

Alternatively, I am happy to host the docs on my personal space as I have done with casbin4d. 

2. The doc generator scans the unit files and generates the html files. it can also generate chm file. Additional information can be added in comments in specific format (see this: http://edn.embarcadero.com/article/42394)

3. What kind of details do you mean and where? I think it is more difficult to change the way the html files appear. If you mean more details in the documentation of methods, classes, etc you can easily do it (see #2)

We can try it if you like. You can create a new repo so we do not pollute the main repo with html files (and they are quite many), I folk it and add some units so everybody has access to the files. 

I will, also, setup a subdomain on my website and we see how it looks. If we decide it doesn't  work, it is easy to delete the repo and the subdomain.

**Comment by fundamentalslib** [comment]
Ok, lets try it out. I have created a repository here:

https://github.com/fundamentalslib/fundamentalsdoc

**Comment by casteng** [comment]
There are tools like DiPasDoc which I've used to generate API documentation from comments in sources.
It's free and generates HTML as well as CHM.

**Comment by jkour** [comment]
I've added a few files here: http://fundamentals5.kouraklis.com/

What do you think?

**Comment by Bi0T1N** [comment]
I'd recommend to use open-source [PasDoc](https://github.com/pasdoc/pasdoc) ([PasDoc Wiki](https://github.com/pasdoc/pasdoc/wiki)).

Some generated documentation examples:

- [Pasdoc Sources](http://pasdoc.sourceforge.net/autodoc/html/index.html)

- [Castle Game Engine](https://castle-engine.io/apidoc/html/index.html)

- [Internet-Tools](http://www.benibela.de/documentation/internettools/)

If you setup Travis CI for the repo, it could simply auto-generate documentation after every commit.
You could host the documentation then with [GitHub Pages](https://pages.github.com/) through this repo [Configuring a publishing source for GitHub Pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages)

**Comment by jkour** [comment]
Hi David,

I have now created docs for the whole fundamentals5 library. It is avail here: [http://fundamentals5.kouraklis.com/](http://fundamentals5.kouraklis.com/)

I have, also, populated the repo in case someone wants to get the files. 

I use the online docs for myself so if people find it useful they are welcome to use the link. In fact, the repo is not really needed.

Regards

**Comment by maxkleiner** [comment]
Hi John
This is a useful work with the documentation and above all the index search is on my top.
Thanks, Max

**Comment by jkour** [comment]
@maxkleiner Thanks. TBH I wasn't aware that anyone ever checks it 👍 

I need to update it to the latest release of the library.

One thing that annoys me a bit is that the source code is very well documents but the app I use does not extract those comments. It only treats the classic XML delphi comments.

By any chance, does anyone know if there is a way to convert/extract/??? the comments and convert them to XML? That would be nice IMHO

**Comment by maxkleiner** [comment]
@jkour I made an article about the fundamentals lib in the latest blaise pascal magazine , mentioned also your docu site.
Content Issue 91
 Fundamentals 5 Code Library
is a big toolbox for Delphi and FreePascal / By Max Kleiner
News from the future: Scrollable Phones and Screens
Lazarus, Atom and Visual Studio ....

**Comment by jkour** [comment]
@maxkleiner Great to give to the library some exposure:-)

**Comment by jkour** [comment]
@maxkleiner I read your article. Great stuff!

And again thanks for the mention
