### ISSUE TITLE
Bug in calling CompareMemNoAsciiCase() in flcHTMLElements.pas

### ISSUE THREAD

**Issue by adem0x** [fundamentalslib/fundamentals5#28]
in flcHTMLElements.pas

in function htmlGetTagIDPtrA();

this portion 
CompareMemNoAsciiCase(Name^, Pointer(P^.Name)^, NameLen)
should be
CompareMemNoAsciiCase(Name^, Pointer(AnsiString(P^.Name))^, NameLen)

and similarly, in function htmlGetAttrIDPtrA()
this portion 
CompareMemNoAsciiCase(Name^, Pointer(htmlAttributeTable[Result])^, NameLen)
should be
CompareMemNoAsciiCase(Name^, Pointer(AnsiString(htmlAttributeTable[Result]))^, NameLen)

Otherwise, CompareMemNoAsciiCase() fails.

Could you please add those typecasts.

**Comment by casteng** [comment]
@adem0x 
Why not to make a pull request?

**Comment by adem0x** [comment]
I am not comfortable with Git.
You're, however, welcome to do so --if you please.

**Comment by butlerdj** [comment]
Fixed in commit https://github.com/fundamentalslib/fundamentals5/commit/96c19b505e4f21c2366ea1bf19b5235722a46705
