### ISSUE TITLE
TF5HTTPClient HTTPS using

### ISSUE THREAD

**Issue by NerfDoriftar** [fundamentalslib/fundamentals5#30]
Hello, i didn't find any information about http client component.
So the question is: how to set HTTPS connection as example for "google.com"?
I tried to change "usehttps" property, but this no helps.

**Comment by butlerdj** [comment]
Hi. You will have to modify flcTCP.inc to {$DEFINE TLS}, modify flcHTTP.inc to {$DEFINE HTTP_TLS} and then recompile with the TLS units included.

Note: Only a very limited number of key exchange and ciphers are supported by the TLS units. Also the TLS units have not been updated in a very long time to keep up with changing standards.

**Comment by NerfDoriftar** [comment]
Thank you for your answer, but, can you explain where i need to modify this?
You mean replace  flcTCP.inc to {$DEFINE TLS} in tcp units?

**Comment by butlerdj** [comment]
TLS/HTTPS has been updated to support DHE_RSA cipher, this gives access to more modern clients/servers.
