### ISSUE TITLE
Compile error - Duplicate identifier 

### ISSUE THREAD

**Issue by benibela** [fundamentalslib/fundamentals5#31]
fpc 3.3 r40721 does not like it when function arguments have the same name as a property

>flcDataStructs.pas(343,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(344,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(378,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(379,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(384,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(420,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(421,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(426,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(471,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(472,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(477,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(513,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(514,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(519,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(564,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(565,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(570,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(606,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(607,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(612,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(648,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(649,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(654,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(690,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(691,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(696,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(733,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(734,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(739,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(776,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(777,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(782,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(824,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(825,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(830,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(863,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(864,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(869,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(905,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(906,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(911,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(944,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(945,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(950,31) Error: Duplicate identifier "Count"
flcDataStructs.pas(987,48) Error: Duplicate identifier "Count"
flcDataStructs.pas(996,27) Error: Duplicate identifier "Item"
flcDataStructs.pas(996,48) Error: Duplicate identifier "ClassType"
flcDataStructs.pas(997,27) Error: Duplicate identifier "Item"
flcDataStructs.pas(997,48) Error: Duplicate identifier "ClassName"
flcDataStructs.pas(998,26) Error: Duplicate identifier "ClassType"
flcDataStructs.pas(998,26) Verbose: There were 50 errors compiling module, stopping

**Comment by butlerdj** [comment]
Thanks for letting me know. I'm on fpc 3.0.4 which seems to compile it. Will have a look the newer builds. Has anything beyond 3.0.4 been released officially?

**Comment by benibela** [comment]
No, but it [should have been](https://forum.lazarus.freepascal.org/index.php/topic,42265.msg324366.html#msg324366)

**Comment by butlerdj** [comment]
This commit https://github.com/fundamentalslib/fundamentals5/commit/7fd38c75eca0e7c86ff7d6a5a4bcac40df5a6033 renames all the duplicate parameters I could find.

I haven't tested with fpc 3.3 though.
