### ISSUE TITLE
CompareMemNoAsciiCase not present

### ISSUE THREAD

**Issue by martinjmoore** [fundamentalslib/fundamentals5#34]
Unit flcStreams

AReaderEx.Match contains a call to CompareMemNoAsciiCase
This is listed in the documentation but doesn't exist. 
CompareMemNoAsciiCaseB and CompareMemNoAsciiCaseW do exist.

My project won't compile and I don't want to guess which to use and start changing code I don't understand :)

**Comment by butlerdj** [comment]
Unit has been updated with this commit:

https://github.com/fundamentalslib/fundamentals5/commit/b91a80a286d244356284f44b609bd73898b6302e

**Comment by martinjmoore** [comment]
> Unit has been updated with this commit:
> 
> [b91a80a](https://github.com/fundamentalslib/fundamentals5/commit/b91a80a286d244356284f44b609bd73898b6302e)

Many thanks, great response!!
